default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: flake8
        args: [--config, setup.cfg]

  -   repo: local
      hooks:
        -   id: changelogs-py
            name: changelogs must be py
            entry: changelog filenames must end in .py
            language: fail
            files: 'changelog/.*(?<!\.py)$'

exclude: '^$'
fail_fast: false
